@baseUrl = https://localhost:5248

### Obtener empresa por id
GET https://localhost:5248/api/Empresa


Accept: application/json

### Actualizar empresa
POST https://localhost:5248/api/Empresa/update/4
Content-Type: application/json
Accept: application/json

{
  "idEmpresa": 4,
  "nombre": "OXXO",
  "descripcion": "Siempre listos siempre hola",
  "rowVersion": "AAAAAAAARlE="
}

####hola
POST https://localhost:5248/api/Empresa
Content-Type: application/json
Accept: application/json

{
  "idEmpresa": 4,
  "nombre": "OXXO",
  "descripcion": "Siempre listos siempre ahi.",
  "rowVersion": "AAAAAAAARlE="
}


### Login
POST https://localhost:5248/api/LogIn/login
Content-Type: application/json
Accept: application/json

{
  "identificador": "holacomoestas@gmail.com",
  "contrasena": "batmaneljefe"
}


### copias el set cookie desde el login 
### Probar endpoint protegido con access token
GET https://localhost:5248/api/test/omg
Accept: application/json
Set-Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NTYiLCJqdGkiOiI1ZTE5ZDg4Ni0zZTAzLTQ5ZmEtOTZlNy1kYjhmZTA1ZGQxZDkiLCJlbWFpbCI6ImhvbGFjb21vZXN0YXNAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbGVhZG8iLCJleHAiOjE3Nzg2MzQyMzUsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyOTMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MjkzIn0.65WjYvC7eZtPnNTUKRUlUTCScH2m3VWISULSeFDkhBw


### test
GET {{baseUrl}}/api/empresa/test